In [1]:
# Data handling
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor

# Model evaluation
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Save model
import joblib

In [2]:
df = pd.read_csv("Retailstores_Cleaned.csv")

In [3]:
df.head()

,Bill_ID,Date,Product_Name,Category,Brand,Quantity,Selling_Price,Cost_Price,Payment_Mode,Revenue,Profit,Month,Day
0,B0001,2026-02-14 00:00:00,Rice,Grocery,Aashirvaad,11,60,50,CASH,660,110,February,Saturday
1,B0002,2026-01-31 00:00:00,Detergent,Household,Surf Excel,2,220,190,UPI,440,60,January,Saturday
2,B0003,2026-06-11 00:00:00,Chips,Snacks,Lays,8,20,12,UPI,160,64,June,Thursday
3,B0004,2026-06-02 00:00:00,Chips,Snacks,Lays,13,20,12,CASH,260,104,June,Tuesday
4,B0005,2026-01-05 00:00:00,Soap,Personal Care,Lux,10,40,30,CASH,400,100,January,Monday

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Bill_ID        990 non-null    object
 1   Date           990 non-null    object
 2   Product_Name   990 non-null    object
 3   Category       990 non-null    object
 4   Brand          990 non-null    object
 5   Quantity       990 non-null    int64
 6   Selling_Price  990 non-null    int64
 7   Cost_Price     990 non-null    int64
 8   Payment_Mode   990 non-null    object
 9   Revenue        990 non-null    int64
 10  Profit         990 non-null    int64
 11  Month          990 non-null    object
 12  Day            990 non-null    object
dtypes: int64(5), object(8)
memory usage: 100.7+ KB

In [5]:
df.columns

Index(['Bill_ID', 'Date', 'Product_Name', 'Category', 'Brand', 'Quantity',
       'Selling_Price', 'Cost_Price', 'Payment_Mode', 'Revenue', 'Profit',
       'Month', 'Day'],
      dtype='object')

In [6]:
X = df[['Category', 'Brand', 'Quantity', 'Selling_Price', 'Cost_Price', 'Payment_Mode', 'Month']]
y = df['Revenue']

print(X.head())
print(y.head())

        Category       Brand  Quantity  Selling_Price  Cost_Price  \
0        Grocery  Aashirvaad        11             60          50
1      Household  Surf Excel         2            220         190
2         Snacks        Lays         8             20          12
3         Snacks        Lays        13             20          12
4  Personal Care         Lux        10             40          30

  Payment_Mode     Month
0         CASH  February
1          UPI   January
2          UPI      June
3         CASH      June
4         CASH   January
0    660
1    440
2    160
3    260
4    400
Name: Revenue, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder

le_category = LabelEncoder()
le_brand = LabelEncoder()
le_payment = LabelEncoder()
le_month = LabelEncoder()

X['Category'] = le_category.fit_transform(X['Category'])
X['Brand'] = le_brand.fit_transform(X['Brand'])
X['Payment_Mode'] = le_payment.fit_transform(X['Payment_Mode'])
X['Month'] = le_month.fit_transform(X['Month'])

print(X.head())

   Category  Brand  Quantity  Selling_Price  Cost_Price  Payment_Mode  Month
0         2      0        11             60          50             1      1
1         3      8         2            220         190             2      2
2         5      5         8             20          12             2      3
3         5      5        13             20          12             1      3
4         4      6        10             40          30             1      2

/tmp/ipykernel_1358/979971189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Category'] = le_category.fit_transform(X['Category'])
/tmp/ipykernel_1358/979971189.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Brand'] = le_brand.fit_transform(X['Brand'])
/tmp/ipykernel_1358/979971189.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Payment_Mode'] = le_payment.fit_transform(X['Payment_Mode'])
/tmp/ipykernel_1358/979971189.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Month'] = le_month.fit_transform(X['Month'])

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (792, 7)
Testing data: (198, 7)

In [9]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [10]:
y_pred = model.predict(X_test)

print("First 10 Predictions:")
print(y_pred[:10])

First 10 Predictions:
[ 30.1  90.  219.2 420.  825.  450.  204.  119.9  60.5 555. ]

In [11]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Root Mean Squared Error:", rmse)
print("R² Score:", r2)

Mean Absolute Error: 4.578787878787881
Root Mean Squared Error: 12.514558189031955
R² Score: 0.999715138535548

In [12]:
import pandas as pd

comparison = pd.DataFrame({
    "Actual Revenue": y_test.values,
    "Predicted Revenue": y_pred
})

comparison.head(10)

   Actual Revenue  Predicted Revenue
0              30               30.1
1              90               90.0
2             220              219.2
3             420              420.0
4             825              825.0
5             450              450.0
6             200              204.0
7             120              119.9
8              60               60.5
9             540              555.0

In [13]:
import joblib

joblib.dump(model, "retail_sales_model.pkl")

print("Model saved successfully!")

Model saved successfully!